# Generated by Django 2.2.5 on 2019-09-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesskey',
            name='key',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
