# Generated by Django 2.2.5 on 2019-09-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190905_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='imprecise_views',
            field=models.IntegerField(default=0),
        ),
    ]
