# Generated by Django 2.2.5 on 2019-10-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190905_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='dynamic_cleaning',
            field=models.BooleanField(default=True),
        ),
    ]
